# Generated by Django 5.2.1 on 2026-04-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_google', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Unidad/Establecimiento')),
                ('path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta Completa (Opcional)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unidad Organizativa Google',
                'verbose_name_plural': 'Unidades Organizativas Google',
            },
        ),
        migrations.AlterModelOptions(
            name='googleuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='googleuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='googleuser',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='googleuploadlog',
            name='total_records',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='googleuser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='googleuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='googleuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='googleuser',
            name='org_unit_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='googleuser',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
