# Generated by Django 5.2.10 on 2026-02-02 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Categoría de Contrato',
                'verbose_name_plural': 'Categorías de Contrato',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado de Contrato',
                'verbose_name_plural': 'Estados de Contrato',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Proceso')),
            ],
            options={
                'verbose_name': 'Proceso de Compra',
                'verbose_name_plural': 'Procesos de Compra',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_mercado_publico', models.CharField(max_length=100, unique=True, verbose_name='Código Mercado Público')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_adjudicacion', models.DateField(verbose_name='Fecha de Adjudicación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de Término')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contratos.categoriacontrato', verbose_name='Categoría')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contratos.estadocontrato', verbose_name='Estado')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contratos.procesocompra', verbose_name='Tipo de Proceso')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
