# Generated by Django 5.2.10 on 2026-02-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrientacionLicitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Orientación / Distribución')),
            ],
            options={
                'verbose_name': 'Orientación de Licitación',
                'verbose_name_plural': 'Orientaciones de Licitación',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='orientacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contratos.orientacionlicitacion', verbose_name='Orientación'),
        ),
    ]
