# Generated by Django 5.2.10 on 2026-02-03 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_orientacionlicitacion_contrato_orientacion'),
        ('servicios', '0009_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='servicios.proveedor', verbose_name='Proveedor'),
        ),
    ]
