# Generated by Django 5.2.10 on 2026-02-03 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_contrato_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Documento')),
                ('archivo', models.FileField(upload_to='contratos/docs/%Y/', verbose_name='Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Documento de Contrato',
                'verbose_name_plural': 'Documentos de Contrato',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='HistorialContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción')),
                ('detalle', models.TextField(verbose_name='Detalle')),
                ('usuario', models.CharField(default='Sistema', max_length=100, verbose_name='Usuario')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Historial de Contrato',
                'verbose_name_plural': 'Historial de Contratos',
                'ordering': ['-fecha'],
            },
        ),
    ]
