# Generated by Django 5.2.10 on 2026-02-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_contrato_nro_oc_contrato_tipo_oc'),
        ('establecimientos', '0008_alter_establecimiento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='establecimientos',
            field=models.ManyToManyField(blank=True, related_name='contratos', to='establecimientos.establecimiento', verbose_name='Establecimientos Asociados'),
        ),
    ]
