# Generated by Django 5.2.10 on 2026-02-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_contrato_cdp_alter_contrato_nro_oc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='monto_total',
            field=models.IntegerField(default=0, verbose_name='Monto Total Adjudicado'),
        ),
    ]
