# Generated by Django 5.2.1 on 2026-04-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_contrato_monto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='monto_consumido_previo',
            field=models.IntegerField(default=0, verbose_name='Monto Consumido Previo'),
        ),
    ]
