# Generated by Django 5.2.1 on 2026-04-29 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_contrato_monto_consumido_previo'),
        ('servicios', '0025_remove_registropago_es_historico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='monto_consumido_previo',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='monto_total',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='proveedor',
        ),
        migrations.CreateModel(
            name='ContratoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_adjudicado', models.IntegerField(default=0, verbose_name='Monto Adjudicado')),
                ('monto_consumido_previo', models.IntegerField(default=0, verbose_name='Monto Consumido Histórico')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_asociados', to='contratos.contrato')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_asociados', to='servicios.proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor de Contrato',
                'verbose_name_plural': 'Proveedores de Contratos',
                'unique_together': {('contrato', 'proveedor')},
            },
        ),
    ]
