# Generated by Django 5.2.1 on 2026-04-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_remove_contrato_monto_consumido_previo_and_more'),
        ('establecimientos', '0012_establecimiento_url_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='establecimientos',
        ),
        migrations.AddField(
            model_name='contratoproveedor',
            name='establecimientos',
            field=models.ManyToManyField(blank=True, to='establecimientos.establecimiento', verbose_name='Establecimientos Asociados'),
        ),
    ]
