# Generated by Django 5.2.1 on 2026-05-06 13:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_remove_contrato_establecimientos_and_more'),
        ('establecimientos', '0012_establecimiento_url_web'),
        ('servicios', '0025_remove_registropago_es_historico'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadoNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Feriado Nacional',
                'verbose_name_plural': 'Feriados Nacionales',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='contratos_f_fecha_16a53c_idx')],
            },
        ),
        migrations.CreateModel(
            name='RutaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('valor_diario', models.IntegerField()),
                ('dia_inicio_periodo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('dia_fin_periodo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('incluir_fines_semana', models.BooleanField(default=False)),
                ('excluir_feriados', models.BooleanField(default=True)),
                ('establecimientos', models.ManyToManyField(to='establecimientos.establecimiento')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.proveedor')),
            ],
            options={
                'verbose_name': 'Ruta de Transporte',
                'verbose_name_plural': 'Rutas de Transporte',
            },
        ),
        migrations.CreateModel(
            name='PeriodoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('mes_referencia', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('anio_referencia', models.IntegerField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto (Editable)'), ('CERRADO', 'Cerrado (Solo Lectura)')], default='ABIERTO', max_length=20)),
                ('monto_total_calculado', models.IntegerField(blank=True, help_text='Snapshot del cálculo al cerrar el periodo', null=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='contratos.rutatransporte')),
            ],
            options={
                'verbose_name': 'Periodo de Cobro',
                'verbose_name_plural': 'Periodos de Cobro',
            },
        ),
        migrations.CreateModel(
            name='ServicioContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(default='TRANSPORTE', max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_operativos', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Servicio de Contrato',
                'verbose_name_plural': 'Servicios de Contrato',
            },
        ),
        migrations.AddField(
            model_name='rutatransporte',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='contratos.serviciocontrato'),
        ),
        migrations.CreateModel(
            name='AusenciaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='contratos.periodocobro')),
            ],
            options={
                'verbose_name': 'Ausencia de Ruta',
                'verbose_name_plural': 'Ausencias de Ruta',
                'indexes': [models.Index(fields=['periodo', 'fecha'], name='contratos_a_periodo_9dddac_idx')],
                'unique_together': {('periodo', 'fecha')},
            },
        ),
        migrations.AddIndex(
            model_name='periodocobro',
            index=models.Index(fields=['ruta', 'fecha_inicio'], name='contratos_p_ruta_id_c76381_idx'),
        ),
        migrations.AddIndex(
            model_name='periodocobro',
            index=models.Index(fields=['mes_referencia', 'anio_referencia'], name='contratos_p_mes_ref_0423cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='periodocobro',
            unique_together={('ruta', 'fecha_inicio', 'fecha_fin')},
        ),
    ]
