# Generated by Django 5.2.1 on 2026-05-06 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0012_feriadonacional_rutatransporte_periodocobro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicioOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(default='Truck', help_text='Nombre del icono de Lucide', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio Operativo',
                'verbose_name_plural': 'Tipos de Servicios Operativos',
            },
        ),
        migrations.AlterField(
            model_name='serviciocontrato',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='contratos.tiposerviciooperativo'),
        ),
    ]
