# Generated by Django 5.2.1 on 2026-05-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_tiposerviciooperativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutatransporte',
            name='itinerario',
            field=models.TextField(blank=True, help_text='Detalle del trayecto (ej: Iquique - Chipana)', null=True),
        ),
    ]
