# Generated by Django 5.2.1 on 2026-05-08 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_rutatransporte_itinerario'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPresetRutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rutas', models.ManyToManyField(related_name='en_grupos', to='contratos.rutatransporte')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_preset', to='contratos.serviciocontrato')),
            ],
            options={
                'verbose_name': 'Grupo de Rutas (Preset)',
                'verbose_name_plural': 'Grupos de Rutas (Presets)',
                'ordering': ['nombre'],
            },
        ),
    ]
