# Generated by Django 5.2.1 on 2026-05-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0015_grupopresetrutas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grupopresetrutas',
            unique_together={('servicio', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='rutatransporte',
            unique_together={('servicio', 'nombre')},
        ),
    ]
