# Generated by Django 5.2.16 on 2026-08-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0016_alter_grupopresetrutas_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviciocontrato',
            options={'ordering': ['nombre', 'id'], 'verbose_name': 'Servicio de Contrato', 'verbose_name_plural': 'Servicios de Contrato'},
        ),
        migrations.AlterModelOptions(
            name='tiposerviciooperativo',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Servicio Operativo', 'verbose_name_plural': 'Tipos de Servicios Operativos'},
        ),
    ]
