# Generated by Django 5.2.15 on 2026-08-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0021_contrato_plantilla_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodocobro',
            name='monto_fijo',
            field=models.IntegerField(blank=True, default=0, help_text='Componente fijo del periodo (modalidad fijo y/o variable).', null=True),
        ),
        migrations.AddField(
            model_name='periodocobro',
            name='monto_variable',
            field=models.IntegerField(blank=True, default=0, help_text='Componente variable del periodo (consumo / extra).', null=True),
        ),
        migrations.AlterField(
            model_name='serviciocontrato',
            name='modalidad_cobro',
            field=models.CharField(choices=[('DIARIO', 'Valor diario (transporte)'), ('MENSUAL_UNICO', 'Monto mensual igual en todos los colegios'), ('MENSUAL_POR_EST', 'Monto mensual distinto por colegio'), ('MENSUAL_FIJO_VARIABLE', 'Mensual fijo y/o variable (por periodo)')], db_index=True, default='DIARIO', max_length=30),
        ),
    ]
