# Generated by Django 5.2.15 on 2026-08-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0022_recepcion_servicio_y_cobros'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodocobro',
            name='fecha_servicio',
            field=models.DateField(blank=True, help_text='Fecha del servicio (opcional; p. ej. fumigación).', null=True),
        ),
        migrations.AddField(
            model_name='periodocobro',
            name='nro_factura',
            field=models.CharField(blank=True, default='', help_text='N° factura / certificado de servicio (captura manual, no transporte).', max_length=100),
        ),
    ]
