# Generated by Django 5.2.15 on 2026-08-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0023_periodo_factura_fecha_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodocobro',
            name='incluir_periodo_en_rc',
            field=models.BooleanField(default=True, help_text='Si es falso, rs_periodo va vacío en el PDF (evita conflicto con fecha de servicio).'),
        ),
    ]
