# Generated by Django 5.2.15 on 2026-08-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0024_periodo_incluir_periodo_en_rc'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodocobro',
            name='fecha_recepcion',
            field=models.DateField(blank=True, help_text='Fecha de la recepción conforme. Si está vacío, al PDF se usa la fecha del día.', null=True),
        ),
    ]
