# Generated by Django 5.2.15 on 2026-08-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0025_periodo_fecha_recepcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodocobro',
            name='fecha_recepcion',
        ),
    ]
