# Generated by Django 5.2.15 on 2026-08-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0026_remove_periodo_fecha_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='detalle',
            field=models.CharField(blank=True, default='', help_text='Texto corto opcional para documentos (ej. recepción de servicio). Si está vacío, las plantillas pueden usar la descripción completa.', max_length=255, verbose_name='Detalle'),
        ),
    ]
