# Generated by Django 5.2.15 on 2026-08-25 20:40

from django.db import migrations, models


def marcar_transporte_sin_iva(apps, schema_editor):
    Contrato = apps.get_model('contratos', 'Contrato')
    Contrato.objects.filter(plantilla_cobro='TRANSPORTE').update(aplica_iva=False)


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0027_contrato_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='aplica_iva',
            field=models.BooleanField(
                default=True,
                help_text=(
                    'Si está activo, las recepciones calculan IVA 19% sobre el neto. '
                    'Transporte suele ir sin IVA.'
                ),
                verbose_name='Aplica IVA',
            ),
        ),
        migrations.RunPython(marcar_transporte_sin_iva, migrations.RunPython.noop),
    ]
