# Generated by Django 5.2.15 on 2026-08-26 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0029_revert_transporte_aplica_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='aplica_iva',
            field=models.BooleanField(default=True, help_text='Si está activo, las recepciones calculan IVA 19% sobre el neto.', verbose_name='Aplica IVA'),
        ),
        migrations.CreateModel(
            name='AmpliacionContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_termino_anterior', models.DateField(help_text='Fecha de término del contrato al momento de registrar la ampliación.', verbose_name='Término previo')),
                ('fecha_inicio', models.DateField(help_text='Por defecto coincide con el término previo; puede ajustarse si hay un salto.', verbose_name='Inicio de la ampliación')),
                ('fecha_termino', models.DateField(verbose_name='Nuevo término')),
                ('nro_resolucion', models.CharField(blank=True, default='', max_length=100, verbose_name='N° resolución / referencia')),
                ('motivo', models.TextField(blank=True, default='', verbose_name='Motivo / glosa')),
                ('documento', models.FileField(blank=True, null=True, upload_to='contratos/ampliaciones/%Y/', verbose_name='Documento de ampliación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, default='', max_length=100, verbose_name='Usuario')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ampliaciones', to='contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Ampliación de contrato',
                'verbose_name_plural': 'Ampliaciones de contrato',
                'ordering': ['-fecha_termino', '-created_at'],
            },
        ),
    ]
