# Generated by Django 5.2.15 on 2026-08-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0030_ampliacion_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='ampliacioncontrato',
            name='monto',
            field=models.IntegerField(blank=True, help_text='Monto adicional asociado a la ampliación (opcional).', null=True, verbose_name='Monto de la ampliación'),
        ),
    ]
