# Generated by Django 5.2.15 on 2026-08-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0031_ampliacion_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ampliacioncontrato',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dato informativo (ej. % sobre el contrato original). No se usa para cálculos.', max_digits=6, null=True, verbose_name='% de ampliación'),
        ),
    ]
