# Generated by Django 5.2.15 on 2026-08-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0032_ampliacion_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='aplica_iva',
            field=models.BooleanField(default=True, help_text='Si está activo, el monto total de gestión se desglosa en neto + IVA 19% al registrar la recepción de Mercado Público.', verbose_name='Aplica IVA'),
        ),
    ]
