# Generated by Django 5.2.16 on 2026-08-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0017_alter_serviciocontrato_options_and_more'),
        ('contratos', '0033_alter_contrato_aplica_iva'),
    ]

    operations = [
    ]
