# Generated by Django 5.2.15 on 2026-08-31 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0036_cobro_volumetrico_m3'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumenDiaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('volumen_m3', models.DecimalField(decimal_places=3, max_digits=12)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumenes_dia', to='contratos.periodocobro')),
            ],
            options={
                'verbose_name': 'Volumen diario del periodo',
                'verbose_name_plural': 'Volúmenes diarios del periodo',
                'indexes': [models.Index(fields=['periodo', 'fecha'], name='contratos_v_periodo_bc429f_idx')],
                'unique_together': {('periodo', 'fecha')},
            },
        ),
    ]
