# Generated by Django 5.2.15 on 2026-09-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0040_ampliacion_monto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocontrato',
            name='activa',
            field=models.BooleanField(db_index=True, default=True, help_text='False = archivada (historial tras cambio de plantilla de cobro).', verbose_name='Gestión activa'),
        ),
        migrations.AddField(
            model_name='serviciocontrato',
            name='archivada_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archivada el'),
        ),
        migrations.AddField(
            model_name='serviciocontrato',
            name='plantilla_cobro',
            field=models.CharField(blank=True, choices=[('TRANSPORTE', 'Transporte (valor diario)'), ('OTRO', 'Otro (monto mensual)'), ('VOLUMETRICO', 'Volumétrico ($/m³)')], db_index=True, help_text='Plantilla con la que operó esta gestión (útil en historial).', max_length=20, null=True, verbose_name='Plantilla de cobro (origen)'),
        ),
    ]
