# Generated by Django 5.2.15 on 2026-09-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0041_serviciocontrato_activa_historial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='serviciocontrato',
            name='unique_gestion_por_contrato',
        ),
        migrations.AddConstraint(
            model_name='serviciocontrato',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('contrato',), name='unique_gestion_activa_por_contrato'),
        ),
    ]
