# Generated by Django 5.2.1 on 2026-07-06 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0005_funcionario_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudARCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_derecho', models.CharField(choices=[('RECTIFICACION', 'Rectificación de Datos'), ('SUPRESION', 'Supresión (Baja de Registro)'), ('PORTABILIDAD', 'Portabilidad de Datos')], default='RECTIFICACION', max_length=20)),
                ('campo', models.CharField(blank=True, help_text="Nombre del campo a cambiar, ej: 'anexo'", max_length=50, null=True)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_propuesto', models.TextField(blank=True, null=True)),
                ('justificacion', models.TextField(help_text='Motivo de la solicitud (Requerido por Art. 11)')),
                ('archivo_respaldo', models.FileField(blank=True, null=True, upload_to='arco/respaldos/%Y/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADA', 'Aprobada y Aplicada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Motivo escrito obligatorio si se rechaza', null=True)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_arco_resueltas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_arco', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Solicitud ARCO',
                'verbose_name_plural': 'Solicitudes ARCO',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
