# Generated by Django 5.2.1 on 2026-07-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudarco',
            name='solicita_bloqueo',
            field=models.BooleanField(default=False, verbose_name='Solicita Bloqueo Temporal (Art. 8° ter)'),
        ),
    ]
