# Generated by Django 5.2.1 on 2026-07-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arco', '0002_solicitudarco_solicita_bloqueo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudarco',
            name='tipo_derecho',
            field=models.CharField(choices=[('RECTIFICACION', 'Rectificación de Datos'), ('SUPRESION', 'Supresión (Baja de Registro)'), ('OPOSICION', 'Oposición al Tratamiento'), ('PORTABILIDAD', 'Portabilidad de Datos')], default='RECTIFICACION', max_length=20),
        ),
    ]
