# Generated by Django 5.2.1 on 2026-04-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_linkinteres'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkinteres',
            name='tipo',
            field=models.CharField(choices=[('LINK', 'Link de Interés'), ('RED_SOCIAL', 'Red Social')], default='LINK', max_length=20, verbose_name='Tipo'),
        ),
    ]
