# Generated by Django 5.2.1 on 2026-04-16 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_linkinteres_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_enabled',
            field=models.BooleanField(default=False, verbose_name='MFA Activo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mfa_method',
            field=models.CharField(choices=[('TOTP', 'App de Autenticación'), ('EMAIL', 'Correo Electrónico')], default='TOTP', max_length=20, verbose_name='Método MFA Preferido'),
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(default='Dispositivo conocido', max_length=100)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo de Confianza',
                'verbose_name_plural': 'Dispositivos de Confianza',
            },
        ),
    ]
