# Generated by Django 5.2.1 on 2026-04-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mfasession_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='Servidor SMTP')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='Puerto SMTP')),
                ('smtp_user', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Usuario SMTP')),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('smtp_use_ssl', models.BooleanField(default=False, verbose_name='Usar SSL')),
                ('default_from_email', models.CharField(default='SLEP Iquique <noreply@slepiquique.cl>', max_length=255, verbose_name='Remitente por Defecto')),
                ('reservas_admin_email', models.EmailField(default='ssgg@slepiquique.cl', help_text='Email que recibe avisos de nuevas reservas', max_length=254, verbose_name='Email Admin Reservas')),
            ],
            options={
                'verbose_name': 'Configuración de Correo',
                'verbose_name_plural': 'Configuraciones de Correo',
            },
        ),
    ]
