# Generated by Django 5.2.1 on 2026-02-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursoreservable',
            name='color',
            field=models.CharField(default='#6366f1', help_text='Color hexadecimal, ej: #6366f1', max_length=7, verbose_name='Color en Calendario'),
        ),
    ]
