# Generated by Django 5.2.1 on 2026-02-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reservas', '0004_alter_solicitudreserva_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudreserva',
            name='email_contacto',
            field=models.EmailField(blank=True, help_text='Correo para notificaciones (especialmente para externos)', max_length=254, null=True, verbose_name='Email de Contacto'),
        ),
    ]
