# Generated by Django 5.2.1 on 2026-04-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reservas', '0009_solicitudreserva_codigo_reserva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudreserva',
            options={'ordering': ['-fecha_inicio'], 'permissions': [('can_change_reserva_name', 'Puede cambiar el nombre de la reserva')]},
        ),
    ]
