# Generated by Django 5.2.1 on 2026-04-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reservas', '0010_alter_solicitudreserva_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasetting',
            name='dias_bloqueo_antelacion',
            field=models.IntegerField(default=0, help_text='Bloquea X días desde hoy hacia atrás.', verbose_name='Días Bloqueo Antelación'),
        ),
    ]
