# Generated by Django 5.2.1 on 2026-04-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reservas', '0011_reservasetting_dias_bloqueo_antelacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudreserva',
            options={'ordering': ['-fecha_inicio'], 'permissions': [('can_change_reserva_name', 'Puede cambiar el nombre de la reserva'), ('can_bypass_antelacion', 'Puede saltar bloqueo de antelación')]},
        ),
    ]
