# Generated by Django 5.2.1 on 2026-04-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reservas', '0012_alter_solicitudreserva_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudreserva',
            options={'ordering': ['-fecha_inicio'], 'permissions': [('aprobar_solicitudreserva', 'Puede aprobar o denegar solicitudes de reserva'), ('finalizar_solicitudreserva', 'Puede marcar reservas como finalizadas'), ('view_solicitudreserva_logs', 'Puede ver el historial de cambios y logs de la reserva'), ('manage_solicitudreserva', 'Administración total del módulo de reservas')]},
        ),
    ]
