# Generated by Django 5.2.1 on 2026-04-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reservas', '0013_remove_reservasetting_dias_bloqueo_antelacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudreserva',
            options={'ordering': ['-fecha_inicio'], 'permissions': [('can_change_reserva_name', 'Puede cambiar el nombre de la reserva'), ('can_bypass_antelacion', 'Puede saltar bloqueo de antelación'), ('can_force_delete_reserva', 'Puede eliminar reservas activas (PENDIENTE o APROBADA) mal solicitadas')]},
        ),
    ]
