# Generated by Django 5.2.1 on 2026-04-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reservas', '0015_alter_solicitudreserva_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudreserva',
            options={'ordering': ['-fecha_inicio'], 'permissions': [('can_change_reserva_name', 'Puede cambiar el nombre de la reserva'), ('can_bypass_antelacion', 'Puede saltar bloqueo de antelación'), ('can_force_delete_reserva', 'Puede eliminar permanentemente una reserva'), ('can_view_logs', 'Puede ver historial de cambios (Logs)'), ('can_manage_settings', 'Puede configurar horario y antelación')]},
        ),
    ]
