# Generated by Django 5.2.10 on 2026-01-29 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Llave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ubicacion', models.CharField(blank=True, help_text='Donde se guarda la llave', max_length=100, verbose_name='Ubicación Física')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llaves', to='establecimientos.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Préstamo')),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Devolución')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('llave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='prestamo_llaves.llave')),
                ('usuario_entrega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_entregados', to=settings.AUTH_USER_MODEL)),
                ('usuario_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='prestamo_llaves.solicitante')),
            ],
            options={
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
