# Generated by Django 5.2.10 on 2026-02-18 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_remove_grupo_es_firmante_grupo_jefe'),
        ('prestamo_llaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='funcionario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_solicitante', to='funcionarios.funcionario', verbose_name='Funcionario Vinculado'),
        ),
    ]
