# Generated by Django 5.2.1 on 2026-05-13 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_funcionario_user'),
        ('tickets', '0002_ticketuseractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='area_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_recibidos', to='funcionarios.departamento'),
        ),
    ]
