# Generated by Django 5.2.1 on 2026-07-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_area_destino'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('can_assign_ticket', 'Puede asignar tickets a otros usuarios')], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
