# Generated by Django 5.2.1 on 2026-07-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('can_assign_ticket', 'Puede asignar tickets a otros usuarios'), ('can_view_all_tickets', 'Puede ver todos los tickets creados por cualquier usuario')], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
