# Generated by Django 5.2.1 on 2026-07-06 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0003_tipoprocedimiento_remove_procedimiento_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='archivo',
            field=models.FileField(upload_to='procedimientos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Archivo'),
        ),
    ]
