# Generated by Django 5.2.1 on 2026-07-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0004_alter_procedimiento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='archivo',
            field=models.FileField(upload_to='procedimientos/', verbose_name='Archivo'),
        ),
    ]
