# Generated by Django 5.2.16 on 2026-08-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0005_alter_procedimiento_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoprocedimiento',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documentos'},
        ),
    ]
