# Generated by Django 5.2.10 on 2026-02-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('es_firmante', models.BooleanField(default=False, verbose_name='Es Firmante')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='funcionarios', to='funcionarios.grupo', verbose_name='Grupos'),
        ),
    ]
