# Generated by Django 5.2.10 on 2026-02-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_grupo_funcionario_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
    ]
