# Generated by Django 5.2.16 on 2026-08-05 20:21

import django.db.models.deletion
import firma_digital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0005_funcionario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelloFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to=firma_digital.models.sello_firma_upload_to, verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellos_firma', to='funcionarios.departamento', verbose_name='Departamento')),
                ('subdireccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellos_firma', to='funcionarios.subdireccion', verbose_name='Subdirección')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellos_firma', to='funcionarios.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Sello de firma',
                'verbose_name_plural': 'Sellos de firma',
                'ordering': ['nombre'],
            },
        ),
    ]
