# Generated by Django 5.2.16 on 2026-08-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firma_digital', '0001_sellos_firma_organigrama'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellofirma',
            options={'ordering': ['nombre'], 'permissions': [('can_firmar', 'Puede firmar digitalmente')], 'verbose_name': 'Sello de firma', 'verbose_name_plural': 'Sellos de firma'},
        ),
    ]
