# Generated by Django 5.2.16 on 2026-08-06 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma_digital', '0002_grupo_es_firmante_can_firmar_perm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFirmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Código')),
                ('hash_sha256', models.CharField(db_index=True, max_length=64, verbose_name='Hash SHA-256')),
                ('nombre_archivo', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre de archivo')),
                ('origen', models.CharField(default='prueba', help_text='Módulo o flujo que generó la firma (prueba, rc, contrato, …).', max_length=64, verbose_name='Origen')),
                ('purpose', models.CharField(blank=True, default='', max_length=64, verbose_name='Propósito FirmaGob')),
                ('firmante_nombre', models.CharField(blank=True, default='', max_length=200, verbose_name='Firmante')),
                ('firmante_run', models.CharField(blank=True, default='', max_length=12, verbose_name='RUN firmante')),
                ('firmante_cargo', models.CharField(blank=True, default='', max_length=200, verbose_name='Cargo')),
                ('firmado_en', models.DateTimeField(auto_now_add=True, verbose_name='Firmado en')),
                ('firmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_firmados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
            ],
            options={
                'verbose_name': 'Documento firmado',
                'verbose_name_plural': 'Documentos firmados',
                'ordering': ['-firmado_en'],
            },
        ),
    ]
