# Generated by Django 5.2.16 on 2026-08-06 14:24

import django.db.models.deletion
import firma_digital.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma_digital', '0003_documento_firmado_validador'),
        ('funcionarios', '0007_grupo_es_firmante_can_firmar_perm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(blank=True, max_length=40, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('origen', models.CharField(help_text='rc, contrato, factura, …', max_length=64)),
                ('referencia_id', models.PositiveIntegerField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20)),
                ('archivo_origen', models.FileField(blank=True, null=True, upload_to=firma_digital.models.pendiente_upload_to)),
                ('archivo_firmado', models.FileField(blank=True, null=True, upload_to=firma_digital.models.firmado_upload_to)),
                ('motivo_rechazo', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('firmado_en', models.DateTimeField(blank=True, null=True)),
                ('rechazado_en', models.DateTimeField(blank=True, null=True)),
                ('documento_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendientes', to='firma_digital.documentofirmado')),
                ('firmante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firmas_pendientes', to='funcionarios.funcionario')),
                ('grupo_firmante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_pendientes', to='funcionarios.grupo')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firma pendiente',
                'verbose_name_plural': 'Firmas pendientes',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['estado', 'firmante'], name='firma_digit_estado_24b8bc_idx'), models.Index(fields=['origen', 'referencia_id'], name='firma_digit_origen_664db3_idx')],
            },
        ),
    ]
