# Generated by Django 5.2.16 on 2026-08-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firma_digital', '0004_firma_pendiente_bandeja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellofirma',
            options={'ordering': ['nombre'], 'permissions': [('can_firmar', 'Puede firmar digitalmente'), ('can_probar_firma', 'Puede usar firma digital (prueba)')], 'verbose_name': 'Sello de firma', 'verbose_name_plural': 'Sellos de firma'},
        ),
    ]
