# Generated by Django 5.2.15 on 2026-09-04 16:43

import django.core.validators
import firma_digital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma_digital', '0007_configuracionsellofirma_proporcion_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsellofirma',
            name='alto_pt',
            field=models.PositiveIntegerField(default=84, help_text='Alto total de la caja en el PDF. Default oficial 84. Sugeridos junto al ancho: 280×100 o 320×110.', verbose_name='Alto del sello completo (pt)'),
        ),
        migrations.AlterField(
            model_name='configuracionsellofirma',
            name='ancho_pt',
            field=models.PositiveIntegerField(default=205, help_text='Ancho total de la caja en el PDF. A mayor ancho, el nombre se parte menos. Default oficial 205. Sugeridos: 280 o 320.', verbose_name='Ancho del sello completo (pt)'),
        ),
        migrations.AlterField(
            model_name='configuracionsellofirma',
            name='imagen_firma',
            field=models.FileField(blank=True, help_text='SVG, PNG o JPG. Comparte la zona del logo (izquierda). La derecha es para el texto.', upload_to=firma_digital.models.sello_fondo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('svg', 'png', 'jpg', 'jpeg'))], verbose_name='Imagen de firma'),
        ),
        migrations.AlterField(
            model_name='configuracionsellofirma',
            name='logo',
            field=models.FileField(blank=True, help_text='SVG, PNG o JPG. Se coloca a la izquierda según “% ancho para logo”. La derecha queda libre para el texto de FirmaGob.', upload_to=firma_digital.models.sello_fondo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('svg', 'png', 'jpg', 'jpeg'))], verbose_name='Logo institucional'),
        ),
        migrations.AlterField(
            model_name='configuracionsellofirma',
            name='proporcion_logo_pct',
            field=models.PositiveIntegerField(default=40, help_text='Ancho máximo del logo como % del sello (izquierda, sin deformar; intenta llenar el alto). No controla dónde FirmaGob escribe el texto: ese layout es del proveedor y suele empezar ~al centro/derecha de la caja. Si pone 20% en un sello de 280 pt, el logo cuadrado solo tendrá ~56 pt de lado y verá un hueco grande hasta el texto. Pruebe 35–45% para acercar el logo al texto. Rango 15–70.', verbose_name='% máx. ancho del logo'),
        ),
    ]
