# Generated by Django 5.2.1 on 2026-09-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firma_digital', '0010_acceso_documento_firma'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accesodocumentofirma',
            new_name='firma_digit_origen_58a28b_idx',
            old_name='firma_digit_origen_c5a1e2_idx',
        ),
        migrations.RenameIndex(
            model_name='accesodocumentofirma',
            new_name='firma_digit_pendien_96d10a_idx',
            old_name='firma_digit_pendien_8f3b4a_idx',
        ),
    ]
