# Generated by Django 5.2.1 on 2026-04-20 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBienestar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(default='Heart', help_text='Nombre del icono de Lucide', max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría de Bienestar',
                'verbose_name_plural': 'Categorías de Bienestar',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (Oculto)'), ('PUBLICADO', 'Publicado (Visible)'), ('EXPIRADO', 'Expirado')], default='BORRADOR', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='bienestar.categoriabienestar')),
            ],
            options={
                'ordering': ['orden', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='BeneficioArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='bienestar/archivos/')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(help_text='Ej: imagen, pdf, doc', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='bienestar.beneficio')),
            ],
        ),
    ]
