# Generated by Django 5.2.10 on 2026-01-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='tipo',
            field=models.CharField(choices=[('escuela', 'Escuela'), ('jardin', 'Jardín'), ('liceo', 'Liceo'), ('colegio', 'Colegio'), ('centro_laboral', 'Centro Laboral')], default='escuela', max_length=20, verbose_name='Tipo'),
        ),
    ]
