# Generated by Django 5.2.1 on 2026-02-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0002_alter_establecimiento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelefonoEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('etiqueta', models.CharField(help_text='Ej: Dirección, Secretaría, Portería', max_length=100, verbose_name='Etiqueta')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='establecimientos.establecimiento')),
            ],
            options={
                'verbose_name': 'Teléfono de Establecimiento',
                'verbose_name_plural': 'Teléfonos de Establecimientos',
                'ordering': ['establecimiento', '-es_principal', 'etiqueta'],
            },
        ),
    ]
