# Generated by Django 5.2.1 on 2026-02-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0003_telefonoestablecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='establecimientos/logos/'),
        ),
    ]
