# Generated by Django 5.2.10 on 2026-02-11 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0006_tipoestablecimiento_alter_establecimiento_tipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establecimiento',
            old_name='tipo',
            new_name='tipo_antiguo',
        ),
        migrations.RenameField(
            model_name='establecimiento',
            old_name='tipo_new',
            new_name='tipo',
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='tipo',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='establecimientos',
                to='establecimientos.tipoestablecimiento',
                verbose_name='Tipo',
                null=True,
                blank=True,
            ),
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='tipo_antiguo',
        ),
    ]
