# Generated by Django 5.2.10 on 2026-02-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0009_tipoestablecimiento_area_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Longitud'),
        ),
    ]
