# Generated by Django 5.2.1 on 2026-05-27 15:51

import django.db.models.deletion
import personalizacion_sistema.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimientos', '0012_establecimiento_url_web'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to=personalizacion_sistema.models.login_background_upload_path)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_login_background_images', to=settings.AUTH_USER_MODEL)),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_background_images', to='establecimientos.establecimiento')),
            ],
            options={
                'verbose_name': 'Imagen de fondo de login',
                'verbose_name_plural': 'Imagenes de fondo de login',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['activa', 'orden'], name='personaliza_activa_4fa6a5_idx'), models.Index(fields=['establecimiento'], name='personaliza_estable_b2be13_idx'), models.Index(fields=['fecha_inicio', 'fecha_fin'], name='personaliza_fecha_i_eb2003_idx')],
            },
        ),
    ]
