# Generated by Django 5.2.1 on 2026-03-04 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimientos', '0009_tipoestablecimiento_area_gestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(choices=[('TECNICO_ENLACES', 'Técnico de Enlaces'), ('COORDINADOR_ENLACES', 'Coordinador(a) de Enlaces'), ('ENCARGADO_ENLACE', 'Encargado(a) Enlace'), ('TECNICO_A_ENLACES', 'Técnico/a Enlace'), ('OTRO', 'Otro')], max_length=30, verbose_name='Función')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('tipo_contrato', models.CharField(choices=[('24', '24 - Profesor Titular'), ('25', '25 - Profesor Contrata'), ('27', '27 - Asistentes Educación Plazo Fijo'), ('28', '28 - Asistentes Educación Plazo Indefinido'), ('OTRO', 'Otro')], max_length=10, verbose_name='Tipo de Contrato')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_ti', to='establecimientos.establecimiento', verbose_name='Establecimiento')),
            ],
            options={
                'verbose_name': 'Personal TI',
                'verbose_name_plural': 'Personal TI',
                'ordering': ['establecimiento__nombre', 'funcion', 'nombre_completo'],
            },
        ),
    ]
