# Generated by Django 5.2.1 on 2026-03-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_ti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalti',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='personalti',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
