# Generated by Django 5.2.1 on 2026-04-07 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_ti', '0002_personalti_correo_personalti_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: 24, 25, 27', max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(default='#10b981', max_length=7)),
            ],
            options={
                'verbose_name': 'Tipo de Contrato TI',
                'verbose_name_plural': 'Tipos de Contrato TI',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='FuncionTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#6366f1', help_text='Color hex para la interfaz', max_length=7)),
            ],
            options={
                'verbose_name': 'Función de Personal',
                'verbose_name_plural': 'Funciones de Personal',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='personalti',
            options={'ordering': ['establecimiento__nombre', 'funcion__nombre', 'nombre_completo'], 'verbose_name': 'Personal TI', 'verbose_name_plural': 'Personal TI'},
        ),
        migrations.AlterField(
            model_name='personalti',
            name='tipo_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal', to='personal_ti.contratoti', verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='personalti',
            name='funcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal', to='personal_ti.funcionti', verbose_name='Función'),
        ),
    ]
