# Generated by Django 5.2.1 on 2026-05-14 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimientos', '0012_establecimiento_url_web'),
        ('funcionarios', '0005_funcionario_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requerimiento', models.CharField(max_length=255, verbose_name='Requerimiento / Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción detallada')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de atención')),
                ('respuesta', models.TextField(blank=True, verbose_name='Respuesta')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('RESPONDIDO', 'Respondido'), ('CERRADO', 'Cerrado')], default='PENDIENTE', max_length=20)),
                ('tiempo_gestion_dias', models.IntegerField(default=0, verbose_name='Tiempo total de gestión (días)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones internas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestiones_creadas', to=settings.AUTH_USER_MODEL)),
                ('ejecutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones_realizadas', to='funcionarios.funcionario')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='establecimientos.establecimiento')),
                ('unidad_requerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestiones_solicitadas', to='funcionarios.unidad')),
            ],
            options={
                'verbose_name': 'Gestión de Establecimiento',
                'verbose_name_plural': 'Gestiones de Establecimientos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='gestiones_ejecutivos/')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='ejecutivos.gestionestablecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField(blank=True)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='ejecutivos.gestionestablecimiento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Gestión',
                'verbose_name_plural': 'Historiales de Gestiones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SubtareaGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='ejecutivos.gestionestablecimiento')),
            ],
            options={
                'verbose_name': 'Subtarea de Gestión',
                'verbose_name_plural': 'Subtareas de Gestión',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionEjecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecutivos_asignados', to='establecimientos.establecimiento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos_asignados', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Asignación de Ejecutivo',
                'verbose_name_plural': 'Asignaciones de Ejecutivos',
                'unique_together': {('funcionario', 'establecimiento')},
            },
        ),
    ]
