# Generated by Django 5.2.1 on 2026-05-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejecutivos', '0001_initial'),
        ('funcionarios', '0005_funcionario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestionestablecimiento',
            name='unidad_requerida',
        ),
        migrations.AddField(
            model_name='gestionestablecimiento',
            name='departamentos_requeridos',
            field=models.ManyToManyField(blank=True, related_name='gestiones_solicitadas', to='funcionarios.departamento'),
        ),
        migrations.AddField(
            model_name='gestionestablecimiento',
            name='subdirecciones_requeridas',
            field=models.ManyToManyField(blank=True, related_name='gestiones_solicitadas', to='funcionarios.subdireccion'),
        ),
        migrations.AddField(
            model_name='gestionestablecimiento',
            name='unidades_requeridas',
            field=models.ManyToManyField(blank=True, related_name='gestiones_solicitadas', to='funcionarios.unidad'),
        ),
    ]
