# Generated by Django 5.2.10 on 2026-01-29 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0002_alter_establecimiento_tipo'),
        ('servicios', '0002_tipoproveedor_proveedor_acronimo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(verbose_name='Fecha envío a pago')),
                ('nro_documento', models.CharField(max_length=100)),
                ('monto_interes', models.IntegerField(default=0)),
                ('monto_total', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_servicios', to='establecimientos.establecimiento')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Registro de Pago',
                'verbose_name_plural': 'Registros de Pagos',
            },
        ),
    ]
