# Generated by Django 5.2.10 on 2026-01-29 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_registropago'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionConforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=50, unique=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='servicios.proveedor')),
            ],
            options={
                'verbose_name': 'Recepción Conforme',
                'verbose_name_plural': 'Recepciones Conformes',
            },
        ),
        migrations.AddField(
            model_name='registropago',
            name='recepcion_conforme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='servicios.recepcionconforme'),
        ),
    ]
