# Generated by Django 5.2.10 on 2026-01-29 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_recepcionconforme_registropago_recepcion_conforme'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialRecepcionConforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=100)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=150, null=True)),
                ('recepcion_conforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='servicios.recepcionconforme')),
            ],
            options={
                'verbose_name': 'Historial RC',
                'verbose_name_plural': 'Historial RCs',
                'ordering': ['-fecha'],
            },
        ),
    ]
