# Generated by Django 5.2.10 on 2026-01-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_recepcionconforme_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre CDP')),
                ('archivo', models.FileField(upload_to='cdps/%Y/', verbose_name='Archivo PDF')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción/Observaciones')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CDP (Certificado Disp. Presupuestaria)',
                'verbose_name_plural': 'Repositorio CDPs',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
