# Generated by Django 5.2.10 on 2026-01-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_cdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdp',
            name='anio',
            field=models.IntegerField(default=2026, verbose_name='Año'),
        ),
    ]
