# Generated by Django 5.2.10 on 2026-02-10 13:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0002_alter_establecimiento_tipo'),
        ('servicios', '0009_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Entrega',
                'verbose_name_plural': 'Tipos de Entrega',
            },
        ),
        migrations.CreateModel(
            name='FacturaAdquisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción de producto o servicio')),
                ('fecha_recepcion', models.DateField(default=datetime.date.today, verbose_name='Fecha de recepción conforme')),
                ('total_neto', models.IntegerField(verbose_name='Total Neto')),
                ('iva', models.IntegerField(verbose_name='Impuestos (19% IVA)')),
                ('total_pagar', models.IntegerField(verbose_name='Total a Pagar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cdp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_adquisicion', to='servicios.cdp', verbose_name='Certificado de Presupuesto')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_adquisicion', to='establecimientos.establecimiento')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_adquisicion', to='servicios.proveedor')),
                ('tipo_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='servicios.tipoentrega', verbose_name='Tipo de Entrega')),
            ],
            options={
                'verbose_name': 'Factura de Adquisición',
                'verbose_name_plural': 'Facturas de Adquisición',
                'ordering': ['-fecha_recepcion'],
            },
        ),
    ]
