# Generated by Django 5.2.10 on 2026-02-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_tipoentrega_facturaadquisicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaadquisicion',
            name='cdp',
            field=models.CharField(max_length=100, verbose_name='Certificado de Presupuesto (CDP)'),
        ),
    ]
