# Generated by Django 5.2.10 on 2026-02-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_alter_facturaadquisicion_cdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaadquisicion',
            name='folio',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Folio RC'),
        ),
    ]
