# Generated by Django 5.2.10 on 2026-02-10 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_grupo_funcionario_grupos'),
        ('servicios', '0013_facturaadquisicion_grupo_firmante'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionconforme',
            name='grupo_firmante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_conformes', to='funcionarios.grupo', verbose_name='Grupo de Firmantes'),
        ),
    ]
