# Generated by Django 5.2.1 on 2026-04-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0022_delete_menusistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='numero_cliente',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
