# Generated by Django 5.2.1 on 2026-04-10 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0023_alter_servicio_numero_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropago',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='servicios.servicio'),
        ),
    ]
