# Generated by Django 5.2.1 on 2026-04-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0023_alter_servicio_numero_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropago',
            name='es_historico',
            field=models.BooleanField(default=False, verbose_name='¿Es registro histórico?'),
        ),
    ]
