# Generated by Django 5.2.1 on 2026-04-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0024_registropago_es_historico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropago',
            name='es_historico',
        ),
    ]
