# Generated by Django 5.2.1 on 2026-04-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0024_alter_registropago_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropago',
            name='nro_servicio_factura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuenta de Facturación / Srv. Corporativo'),
        ),
    ]
