# Generated by Django 5.2.1 on 2026-04-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0025_registropago_nro_servicio_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='numero_servicio',
        ),
    ]
