# Generated by Django 5.2.1 on 2026-04-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0026_remove_servicio_numero_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropago',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registropago',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha envío a pago'),
        ),
    ]
