# Generated by Django 5.2.1 on 2026-04-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0027_alter_registropago_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registropago',
            options={'ordering': ['-fecha_pago'], 'permissions': [('marcar_historico', 'Puede marcar pagos como registros históricos (Salto de RC)')], 'verbose_name': 'Registro de Pago', 'verbose_name_plural': 'Registros de Pagos'},
        ),
    ]
