# Generated by Django 5.2.1 on 2026-04-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Métrica de Dashboard',
                'verbose_name_plural': 'Métricas de Dashboard',
                'ordering': ['-date', 'tag'],
            },
        ),
    ]
