# Generated by Django 5.2.1 on 2026-04-13 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Procedimiento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción o Resumen')),
                ('archivo', models.FileField(upload_to='procedimientos/', verbose_name='Archivo del Procedimiento')),
                ('categoria', models.CharField(choices=[('GENERAL', 'General'), ('RRHH', 'Recursos Humanos'), ('TI', 'Tecnología e Informática'), ('FINANZAS', 'Finanzas y Contabilidad'), ('CONTRATOS', 'Contratos y Adquisiciones'), ('OTROS', 'Otros')], default='GENERAL', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimientos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'ordering': ['-created_at'],
                'permissions': [('can_manage_procedimientos', 'Puede subir y editar procedimientos')],
            },
        ),
    ]
