# Generated by Django 5.2.1 on 2026-04-13 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#6366f1', help_text='Color hexadecimal para la UI', max_length=7)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría de Procedimiento',
                'verbose_name_plural': 'Categorías de Procedimientos',
            },
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimientos', to='procedimientos.categoriaprocedimiento'),
        ),
    ]
