# Generated by Django 5.2.1 on 2026-04-13 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_funcionario_user'),
        ('procedimientos', '0002_categoriaprocedimiento_alter_procedimiento_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.RemoveField(
            model_name='procedimiento',
            name='categoria',
        ),
        migrations.AlterModelOptions(
            name='procedimiento',
            options={'ordering': ['-created_at'], 'verbose_name': 'Procedimiento', 'verbose_name_plural': 'Procedimientos'},
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.departamento'),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='subdireccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.subdireccion'),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.unidad'),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='archivo',
            field=models.FileField(upload_to='procedimientos/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimientos', to='procedimientos.tipoprocedimiento'),
        ),
        migrations.DeleteModel(
            name='CategoriaProcedimiento',
        ),
    ]
