# Generated by Django 5.2.10 on 2026-02-11 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_grupo_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='es_firmante',
        ),
        migrations.AddField(
            model_name='grupo',
            name='jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_liderados', to='funcionarios.funcionario', verbose_name='Jefe de Grupo'),
        ),
    ]
