# Generated by Django 5.2.10 on 2026-02-27 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_remove_grupo_es_firmante_grupo_jefe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema'),
        ),
    ]
