# Generated by Django 5.2.16 on 2026-08-05 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma_digital', '0001_sellos_firma_organigrama'),
        ('funcionarios', '0005_funcionario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='sello_preferido',
            field=models.ForeignKey(blank=True, help_text='Opcional. Si está vacío se usa el sello de Unidad → Departamento → Subdirección.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferido_por', to='firma_digital.sellofirma', verbose_name='Sello de firma preferido'),
        ),
    ]
