# Generated by Django 5.2.16 on 2026-08-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_sellos_firma_organigrama'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='es_firmante',
            field=models.BooleanField(default=False, help_text='Si está activo, los miembros de este grupo pueden firmar digitalmente (además del permiso firma_digital.can_firmar).', verbose_name='Grupo de firmantes'),
        ),
    ]
