# Generated by Django 5.2.1 on 2026-02-13 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoReservable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('SALA', 'Sala de Reuniones'), ('VEHICULO', 'Vehículo'), ('PROYECTOR', 'Proyector/Equipo'), ('OTRO', 'Otro Recurso')], max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('capacidad', models.IntegerField(default=1, verbose_name='Capacidad (Personas)')),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del Evento/Uso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Detalle de Uso')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada por Usuario'), ('FINALIZADA', 'Finalizada/Completada')], default='PENDIENTE', max_length=20)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='solicitudes_reservas.recursoreservable')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
