# Generated by Django 5.2.1 on 2026-02-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reservas', '0002_recursoreservable_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudreserva',
            name='nombre_funcionario',
            field=models.CharField(blank=True, help_text='Nombre de quien usará el recurso', max_length=150, verbose_name='Nombre del Funcionario'),
        ),
    ]
