# Generated by Django 5.2.1 on 2026-02-25 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reservas', '0006_bloqueohorario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloqueohorario',
            options={'ordering': ['fecha_inicio', 'hora_inicio']},
        ),
        migrations.RemoveField(
            model_name='bloqueohorario',
            name='fecha',
        ),
        migrations.AddField(
            model_name='bloqueohorario',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha fin (solo para RANGO)'),
        ),
        migrations.AddField(
            model_name='bloqueohorario',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2026, 2, 25), verbose_name='Fecha inicio del bloqueo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloqueohorario',
            name='modo',
            field=models.CharField(choices=[('DIA', 'Día específico'), ('RANGO', 'Rango de fechas'), ('INDEFINIDO', 'Indefinido (sin fecha de fin)')], default='DIA', max_length=12, verbose_name='Tipo de bloqueo'),
        ),
    ]
