# Generated by Django 5.2.1 on 2026-03-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reservas', '0007_alter_bloqueohorario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(default='07:00', verbose_name='Hora de Inicio Jornada')),
                ('hora_fin', models.TimeField(default='18:00', verbose_name='Hora de Fin Jornada')),
            ],
            options={
                'verbose_name': 'Ajuste de Reservas',
                'verbose_name_plural': 'Ajustes de Reservas',
            },
        ),
    ]
