# Generated by Django 5.2.1 on 2026-04-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reservas', '0008_reservasetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudreserva',
            name='codigo_reserva',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código de Reserva'),
        ),
    ]
