# Generated by Django 5.2.1 on 2026-04-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reservas', '0012_alter_solicitudreserva_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservasetting',
            name='dias_bloqueo_antelacion',
        ),
        migrations.AddField(
            model_name='recursoreservable',
            name='dias_antelacion',
            field=models.IntegerField(default=0, help_text='Días mínimos requeridos para reservar este recurso.', verbose_name='Días de antelación'),
        ),
    ]
