# Generated by Django 5.2.1 on 2026-04-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscuelaRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_lan', models.GenericIPAddressField(help_text='Ej: 192.168.10.1', verbose_name='IP Router LAN')),
                ('ip_wifi', models.GenericIPAddressField(blank=True, help_text='Ej: 10.250.10.1', null=True, verbose_name='IP Router WIFI')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo en Monitoreo')),
                ('last_status_lan', models.BooleanField(default=False)),
                ('last_status_wifi', models.BooleanField(default=False)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('latency_lan', models.IntegerField(default=0, help_text='Latencia en ms')),
            ],
            options={
                'verbose_name': 'Establecimiento (Red)',
                'verbose_name_plural': 'Establecimientos (Red)',
            },
        ),
    ]
