# Generated by Django 5.2.1 on 2026-04-20 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conectividad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuelared',
            name='packet_loss',
            field=models.IntegerField(default=0, help_text='Porcentaje de pérdida'),
        ),
        migrations.AddField(
            model_name='escuelared',
            name='proveedor',
            field=models.CharField(default='GTD', max_length=100),
        ),
        migrations.AddField(
            model_name='escuelared',
            name='tipo_enlace',
            field=models.CharField(choices=[('FIBRA', 'Fibra Óptica'), ('RADIO', 'Radio Enlace'), ('ADSL', 'ADSL / Cobre'), ('STARLINK', 'Satelital (Starlink)')], default='FIBRA', max_length=20),
        ),
        migrations.AddField(
            model_name='escuelared',
            name='velocidad_bajada',
            field=models.IntegerField(default=0, help_text='Mbps contratados'),
        ),
        migrations.CreateModel(
            name='PingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_lan', models.BooleanField()),
                ('latency', models.IntegerField()),
                ('packet_loss', models.IntegerField()),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='conectividad.escuelared')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
