# Generated by Django 5.2.10 on 2026-01-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rbd', models.PositiveIntegerField(db_index=True, verbose_name='RBD')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('escuela', 'Escuela'), ('jardin', 'Jardín'), ('liceo', 'Liceo')], default='escuela', max_length=20, verbose_name='Tipo')),
                ('director', models.CharField(blank=True, max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
