# Generated by Django 5.2.1 on 2026-02-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0004_establecimiento_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='tipo',
            field=models.CharField(choices=[('SALA_CUNA', 'Sala Cuna'), ('JARDIN_INFANTIL', 'Jardín Infantil'), ('ESCUELA', 'Escuela'), ('LICEO', 'Liceo'), ('CENTRO_CAPACITACION', 'Centro de Capacitación'), ('ADMINISTRACION', 'Administración')], default='ESCUELA', max_length=20, verbose_name='Tipo'),
        ),
    ]
