# Generated by Django 5.2.10 on 2026-02-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0005_alter_establecimiento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Establecimiento',
                'verbose_name_plural': 'Tipos de Establecimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='tipo',
            field=models.CharField(choices=[('SALA_CUNA', 'Sala Cuna'), ('JARDIN_INFANTIL', 'Jardín Infantil'), ('ESCUELA', 'Escuela'), ('LICEO', 'Liceo'), ('CENTRO_CAPACITACION', 'Centro de Capacitación'), ('ADMINISTRACION', 'Administración')], default='ESCUELA', max_length=20, verbose_name='Tipo (Antiguo)'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='tipo_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='establecimientos', to='establecimientos.tipoestablecimiento', verbose_name='Tipo'),
        ),
    ]
