# Generated by Django 5.2.10 on 2026-02-11 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0007_migrate_tipo_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='establecimientos', to='establecimientos.tipoestablecimiento', verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
