# Generated by Django 5.2.10 on 2026-02-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0008_alter_establecimiento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoestablecimiento',
            name='area_gestion',
            field=models.CharField(choices=[('ESTABLECIMIENTO', 'Establecimiento (Escuela/Liceo/Colegio)'), ('JARDIN', 'Jardín Infantil VTF'), ('OFICINA', 'Oficina Central / Administración')], default='ESTABLECIMIENTO', max_length=20, verbose_name='Área de Gestión'),
        ),
    ]
