# Generated by Django 5.2.10 on 2026-02-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0010_establecimiento_latitud_establecimiento_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='latitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='longitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
