# Generated by Django 5.2.1 on 2026-04-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0011_alter_establecimiento_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='url_web',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Página Web'),
        ),
    ]
