# Generated by Django 5.2.15 on 2026-08-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0012_establecimiento_url_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='email_director',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo del director/a'),
        ),
    ]
