# Generated by Django 5.2.15 on 2026-08-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0013_establecimiento_email_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='ciudad',
            field=models.CharField(blank=True, default='Iquique', help_text='Ciudad del establecimiento. Por defecto Iquique.', max_length=100, verbose_name='Ciudad'),
        ),
    ]
