# Generated by Django 5.2.1 on 2026-02-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('numero_vehiculos', models.IntegerField(default=0, verbose_name='Número de vehículos')),
                ('kilometros_recorridos', models.IntegerField(default=0, verbose_name='Kilómetros mensuales recorridos')),
                ('unidad_monetaria', models.CharField(default='Pesos', max_length=10, verbose_name='Unidad monetaria')),
                ('gasto_bencina', models.IntegerField(default=0, verbose_name='Monto mensual del gasto en bencina')),
                ('gasto_peajes', models.IntegerField(default=0, verbose_name='Monto mensual del gasto en peajes')),
                ('gasto_seguros', models.IntegerField(default=0, verbose_name='Monto mensual pagado en seguros')),
            ],
            options={
                'verbose_name': 'Registro Mensual de Vehículos',
                'verbose_name_plural': 'Registros Mensuales de Vehículos',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('anio', 'mes')},
            },
        ),
    ]
