# Generated by Django 5.2.1 on 2026-04-08 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.AlterModelOptions(
            name='registromensual',
            options={'ordering': ['-anio', '-mes', 'vehiculo__patente'], 'verbose_name': 'Registro Mensual de Gastos', 'verbose_name_plural': 'Registros Mensuales de Gastos'},
        ),
        migrations.AlterUniqueTogether(
            name='registromensual',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='registromensual',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='vehiculos.vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AlterUniqueTogether(
            name='registromensual',
            unique_together={('anio', 'mes', 'vehiculo')},
        ),
        migrations.RemoveField(
            model_name='registromensual',
            name='numero_vehiculos',
        ),
    ]
