# Generated by Django 5.2.1 on 2026-04-08 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_vehiculo_alter_registromensual_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromensual',
            name='vehiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='vehiculos.vehiculo', verbose_name='Vehículo'),
            preserve_default=False,
        ),
    ]
