# Generated by Django 5.2.15 on 2026-08-10 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimientos', '0012_establecimiento_url_web'),
        ('servicios', '0030_alter_recepcionconforme_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRegistroServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('usa_folio', models.BooleanField(default=False, help_text='Si el tipo usa folio (ej. FMS-2568).')),
                ('prefijo_folio', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de registro de servicio',
                'verbose_name_plural': 'Tipos de registro de servicio',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroServicioDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('fecha_servicio', models.DateField(blank=True, db_index=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentacion_servicios/%Y/%m/')),
                ('valores', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_doc_servicio_creados', to=settings.AUTH_USER_MODEL)),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_doc_servicio', to='establecimientos.establecimiento')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_doc_servicio', to='servicios.proveedor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='documentacion_servicios.tiporegistroservicio')),
            ],
            options={
                'verbose_name': 'Registro de documentación de servicio',
                'verbose_name_plural': 'Registros de documentación de servicio',
                'ordering': ['-fecha_servicio', '-creado_en'],
                'permissions': [('configure_tiporegistroservicio', 'Puede configurar tipos y campos de documentación')],
            },
        ),
        migrations.CreateModel(
            name='CampoDefinicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Identificador interno. Reservadas: folio, proveedor, establecimiento, fecha_servicio, archivo', max_length=60)),
                ('etiqueta', models.CharField(max_length=120)),
                ('tipo_dato', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('boolean', 'Sí/No'), ('select', 'Lista'), ('proveedor', 'Proveedor'), ('establecimiento', 'Establecimiento'), ('file', 'Archivo'), ('folio', 'Folio')], default='text', max_length=20)),
                ('obligatorio', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('opciones', models.JSONField(blank=True, default=list, help_text='Opciones para tipo select: ["A","B"] o [{"value":"a","label":"A"}]')),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='documentacion_servicios.tiporegistroservicio')),
            ],
            options={
                'verbose_name': 'Campo de tipo de registro',
                'verbose_name_plural': 'Campos de tipo de registro',
                'ordering': ['orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'clave'), name='uniq_campodef_tipo_clave')],
            },
        ),
    ]
