# Generated by Django 5.2.15 on 2026-08-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campodefinicion',
            name='dias_aviso',
            field=models.PositiveIntegerField(blank=True, help_text='Solo campos fecha: días antes de la fecha para avisar. Vacío = sin aviso.', null=True),
        ),
        migrations.AddField(
            model_name='registroserviciodoc',
            name='avisos_enviados',
            field=models.JSONField(blank=True, default=dict, help_text='Último aviso por campo: {clave: "YYYY-MM-DD"}'),
        ),
        migrations.AddField(
            model_name='tiporegistroservicio',
            name='notificar_al_crear',
            field=models.BooleanField(default=False, help_text='Si está activo, al crear un registro dispara DOC_SERVICIOS.{codigo}_NUEVO (configurable en panel de tipos de notificación).'),
        ),
    ]
