# Generated by Django 5.2.15 on 2026-08-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion_servicios', '0004_correo_enviado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campodefinicion',
            name='dias_aviso',
            field=models.PositiveIntegerField(blank=True, help_text='Solo campos fecha: primer hito (días antes). También avisa en 60/45/30/20/10/5/1 si aplican.', null=True),
        ),
        migrations.AlterField(
            model_name='registroserviciodoc',
            name='correo_enviado_en',
            field=models.DateTimeField(blank=True, help_text='Última vez que se envió el documento al correo institucional y/o del director/a.', null=True),
        ),
    ]
