# Generated by Django 5.2.1 on 2026-04-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remuneraciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre Banco (como aparece en archivo)')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código Asignado')),
            ],
            options={
                'verbose_name': 'Mapeo de Banco',
                'verbose_name_plural': 'Mapeos de Bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MapeoBancoDirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.CharField(max_length=10, unique=True, verbose_name='Segmento/Código en archivo')),
                ('codigo_completo', models.CharField(max_length=10, verbose_name='Código Banco Completo')),
            ],
            options={
                'verbose_name': 'Mapeo de Banco Directo',
                'verbose_name_plural': 'Mapeos de Bancos Directos',
                'ordering': ['segmento'],
            },
        ),
        migrations.CreateModel(
            name='MapeoMedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Medio de Pago (como aparece en archivo)')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código Asignado')),
            ],
            options={
                'verbose_name': 'Mapeo de Medio de Pago',
                'verbose_name_plural': 'Mapeos de Medios de Pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ValeVistaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Configuración Vale Vista',
                'verbose_name_plural': 'Configuraciones Vale Vista',
            },
        ),
    ]
