# Generated by Django 5.2.1 on 2026-02-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompraMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_externo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('estado_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_estado', models.IntegerField(blank=True, db_index=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('json_data', models.JSONField(blank=True, null=True, verbose_name='Ficha Normalizada')),
                ('is_enriquecida', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden de Compra Mercado Público',
                'verbose_name_plural': 'Órdenes de Compra Mercado Público',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
