# Generated by Django 5.2.1 on 2026-03-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo_llaves', '0002_solicitante_funcionario'),
    ]

    operations = [
        migrations.RenameModel('Llave', 'Activo'),
        migrations.RenameField('Prestamo', 'llave', 'activo'),
    ]
