# Generated by Django 5.2.1 on 2026-03-23 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0011_alter_establecimiento_latitud_and_more'),
        ('prestamo_llaves', '0003_rename_llave_to_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='codigo_inventario',
            field=models.CharField(blank=True, help_text='Opcional. Ej: Placa de inventario o S/N', max_length=50, verbose_name='Código de Inventario'),
        ),
        migrations.AddField(
            model_name='activo',
            name='tipo',
            field=models.CharField(choices=[('LLAVE', 'Llave/Llavero'), ('PROYECTOR', 'Proyector'), ('NOTEBOOK', 'Notebook/Computador'), ('OTRO', 'Otro')], default='LLAVE', max_length=50, verbose_name='Tipo de Activo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='establecimientos.establecimiento'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Donde se guarda físicamente', max_length=100, verbose_name='Ubicación Física'),
        ),
    ]
