# Generated by Django 5.2.1 on 2026-04-07 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo_llaves', '0004_activo_codigo_inventario_activo_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Activo',
                'verbose_name_plural': 'Tipos de Activos',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='activo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='activo',
            name='tipo_legacy',
            field=models.CharField(default='LLAVE', max_length=50, verbose_name='Tipo (Legacy)'),
        ),
        migrations.AddField(
            model_name='activo',
            name='tipo_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='prestamo_llaves.tipoactivo', verbose_name='Tipo de Activo'),
        ),
    ]
