# Generated by Django 5.2.1 on 2026-04-07 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo_llaves', '0005_tipoactivo_remove_activo_tipo_activo_tipo_legacy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='tipo_legacy',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='tipo_new',
        ),
        migrations.AddField(
            model_name='activo',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='prestamo_llaves.tipoactivo', verbose_name='Tipo de Activo'),
            preserve_default=False,
        ),
    ]
