# Generated by Django 5.2.16 on 2026-08-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo_llaves', '0006_remove_activo_tipo_legacy_remove_activo_tipo_new_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activo',
            options={'ordering': ['nombre', 'id'], 'verbose_name': 'Activo', 'verbose_name_plural': 'Activos'},
        ),
    ]
