# Generated by Django 5.2.1 on 2026-04-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='http://52.2.77.197:8081', max_length=255)),
                ('username', models.CharField(default='admin', max_length=100)),
                ('password', models.CharField(default='admin', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Biométrico',
                'verbose_name_plural': 'Configuraciones Biométrico',
            },
        ),
    ]
