# Generated by Django 5.2.1 on 2026-04-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricoArea',
            fields=[
                ('area_code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('area_name', models.CharField(max_length=255)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Establecimiento Biométrico',
                'verbose_name_plural': 'Establecimientos Biométrico',
                'ordering': ['area_name'],
            },
        ),
    ]
