# Generated by Django 5.2.1 on 2026-04-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrico', '0002_biometricoarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricoUsuario',
            fields=[
                ('emp_code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employee_area', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario Biométrico',
                'verbose_name_plural': 'Usuarios Biométrico',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
