# Generated by Django 5.2.1 on 2026-04-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrico', '0003_biometricousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricoTerminal',
            fields=[
                ('terminal_code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('terminal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terminal Biométrico',
                'verbose_name_plural': 'Terminales Biométrico',
                'ordering': ['terminal_name'],
            },
        ),
    ]
