# Generated by Django 5.2.1 on 2026-04-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrico', '0004_biometricoterminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricoarea',
            name='internal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
