# Generated by Django 5.2.1 on 2026-04-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo (ej: Gmail Reservas)', max_length=100)),
                ('slug', models.SlugField(help_text='Identificador único para el código (ej: reservas)', unique=True)),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_host_user', models.CharField(max_length=255)),
                ('email_host_password', models.CharField(help_text='Contraseña o Contraseña de Aplicación', max_length=255)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_use_ssl', models.BooleanField(default=False)),
                ('default_from_email', models.CharField(help_text='Dirección que aparecerá como remitente', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('ultima_prueba', models.DateTimeField(blank=True, null=True)),
                ('resultado_prueba', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Email',
                'verbose_name_plural': 'Configuraciones de Email',
            },
        ),
    ]
