# Generated by Django 5.2.1 on 2026-04-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionEmail',
        ),
    ]
