# Generated by Django 5.2.15 on 2026-08-03 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comunicaciones', '0005_alter_destinatarioscorreooperativo_grupos'),
        ('funcionarios', '0005_funcionario_user'),
        ('notificaciones', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: TICKETS.NUEVO', max_length=80, unique=True)),
                ('modulo', models.CharField(db_index=True, max_length=40)),
                ('evento', models.CharField(db_index=True, max_length=40)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('enviar_campana', models.BooleanField(default=True)),
                ('enviar_email', models.BooleanField(default=False)),
                ('emails_adicionales', models.TextField(blank=True, default='', help_text='Solo canal email. Separados por coma, punto y coma o salto de línea.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de notificación',
                'verbose_name_plural': 'Tipos de notificación',
                'ordering': ['modulo', 'evento'],
            },
        ),
        migrations.AddField(
            model_name='notificacion',
            name='contexto',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='evento',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='modulo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False), models.Q(('dedupe_key', ''), _negated=True)), fields=('usuario', 'dedupe_key'), name='uniq_notif_usuario_dedupe'),
        ),
        migrations.AddField(
            model_name='tiponotificacion',
            name='cuenta_smtp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_notificacion', to='comunicaciones.cuentasmtp', verbose_name='Cuenta SMTP'),
        ),
        migrations.AddField(
            model_name='tiponotificacion',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='tipos_notificacion', to='funcionarios.grupo', verbose_name='Grupos de funcionarios'),
        ),
        migrations.AddField(
            model_name='tiponotificacion',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_notificacion', to='comunicaciones.plantillacorreo', verbose_name='Plantilla de correo'),
        ),
        migrations.AddField(
            model_name='tiponotificacion',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='tipos_notificacion', to='auth.group', verbose_name='Roles (Django)'),
        ),
        migrations.AddField(
            model_name='tiponotificacion',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='tipos_notificacion_destinatario', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios destinatarios'),
        ),
        migrations.AddConstraint(
            model_name='tiponotificacion',
            constraint=models.UniqueConstraint(fields=('modulo', 'evento'), name='uniq_tiponotif_modulo_evento'),
        ),
    ]
