# Generated by Django 5.2.15 on 2026-08-07 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('funcionarios', '0005_funcionario_user'),
        ('notificaciones', '0005_backfill_modulo_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('handler_key', models.CharField(help_text='Clave en JOB_HANDLERS, ej. vehiculos_vencimientos', max_length=80)),
                ('hora', models.TimeField(help_text='Hora local America/Santiago')),
                ('activo', models.BooleanField(default=True)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('ultima_fecha_corrida', models.DateField(blank=True, help_text='Fecha local del último run exitoso (anti-doble en el día)', null=True)),
            ],
            options={
                'verbose_name': 'Job programado',
                'verbose_name_plural': 'Jobs programados',
                'ordering': ['hora', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='FuenteViva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('titulo_bloque', models.CharField(blank=True, default='', help_text='Título opcional en UI; vacío = solo lista de ítems', max_length=120)),
                ('handler_key', models.CharField(help_text='Clave en LIVE_HANDLERS, ej. reservas_pendientes', max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('proposito_operativo', models.CharField(blank=True, default='', help_text='Si no hay destinatarios M2M, reutiliza DestinatariosCorreoOperativo de este propósito.', max_length=50)),
                ('grupos', models.ManyToManyField(blank=True, related_name='fuentes_vivas', to='funcionarios.grupo')),
                ('roles', models.ManyToManyField(blank=True, related_name='fuentes_vivas', to='auth.group')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='fuentes_vivas_destinatario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fuente viva (polling)',
                'verbose_name_plural': 'Fuentes vivas (polling)',
                'ordering': ['orden', 'codigo'],
            },
        ),
    ]
