# Generated by Django 5.2.15 on 2026-08-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0006_fuente_viva_y_job_programado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuenteviva',
            name='proposito_operativo',
            field=models.CharField(blank=True, default='', help_text='Legado. Preferir destinatarios M2M o TipoNotificacion (ej. RESERVAS.AVISO_ADMIN).', max_length=50),
        ),
    ]
