# Generated by Django 5.2.16 on 2026-08-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_alter_notificacion_tipo'),
        ('notificaciones', '0007_alter_fuenteviva_proposito_operativo'),
    ]

    operations = [
    ]
