# Generated by Django 5.2.1 on 2026-04-28 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaSMTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Notificaciones Generales', max_length=100, verbose_name='Nombre de la Cuenta')),
                ('smtp_host', models.CharField(max_length=255, verbose_name='Servidor SMTP')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='Puerto SMTP')),
                ('smtp_user', models.CharField(max_length=255, verbose_name='Usuario/Email SMTP')),
                ('smtp_password', models.CharField(max_length=255, verbose_name='Contraseña SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('smtp_use_ssl', models.BooleanField(default=False, verbose_name='Usar SSL')),
                ('remitente_nombre', models.CharField(default='SGAF', max_length=100, verbose_name='Nombre del Remitente')),
                ('remitente_email', models.EmailField(help_text='Debe ser el mismo que el usuario o uno autorizado', max_length=254, verbose_name='Email del Remitente')),
                ('es_default', models.BooleanField(default=False, verbose_name='Cuenta por Defecto')),
            ],
            options={
                'verbose_name': 'Cuenta SMTP',
                'verbose_name_plural': 'Cuentas SMTP',
            },
        ),
        migrations.CreateModel(
            name='PlantillaCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Plantilla')),
                ('proposito', models.CharField(choices=[('MFA', 'Código MFA (2FA)'), ('RESET_PASSWORD', 'Recuperación de Contraseña'), ('RESERVA_SOLICITUD', 'Nueva Solicitud de Reserva (Usuario)'), ('RESERVA_APROBACION', 'Reserva Aprobada/Rechazada'), ('RESERVA_AVISO_ADMIN', 'Aviso a Admin de Nueva Reserva'), ('TEST', 'Correo de Prueba')], max_length=50, unique=True, verbose_name='Propósito')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto del Correo')),
                ('cuerpo_html', models.TextField(help_text='Puedes usar variables como {{ nombre }}, {{ codigo }}, etc.', verbose_name='Cuerpo HTML')),
                ('cuerpo_texto', models.TextField(blank=True, null=True, verbose_name='Cuerpo de Texto Plano (Opcional)')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cuenta_smtp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comunicaciones.cuentasmtp', verbose_name='Cuenta de Envío Específica')),
            ],
            options={
                'verbose_name': 'Plantilla de Correo',
                'verbose_name_plural': 'Plantillas de Correo',
            },
        ),
    ]
