# Generated by Django 5.2.1 on 2026-05-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0002_alter_plantillacorreo_proposito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillacorreo',
            name='proposito',
            field=models.CharField(choices=[('MFA', 'Código MFA (2FA)'), ('RESET_PASSWORD', 'Recuperación de Contraseña'), ('RESERVA_SOLICITUD', 'Nueva Solicitud de Reserva (Usuario)'), ('RESERVA_APROBACION', 'Reserva Aprobada/Rechazada'), ('RESERVA_AVISO_ADMIN', 'Aviso a Admin de Nueva Reserva'), ('RESERVA_RECORDATORIO', 'Recordatorio de Reserva (Automático)'), ('ALERTA_VENCIMIENTO_VEHICULO', 'Alerta de Vencimiento de Documento Vehicular'), ('TEST', 'Correo de Prueba')], max_length=50, unique=True, verbose_name='Propósito'),
        ),
    ]
