# Generated by Django 5.2.1 on 2026-05-26 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comunicaciones', '0003_alter_plantillacorreo_proposito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinatariosCorreoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposito', models.CharField(choices=[('MFA', 'Código MFA (2FA)'), ('RESET_PASSWORD', 'Recuperación de Contraseña'), ('RESERVA_SOLICITUD', 'Nueva Solicitud de Reserva (Usuario)'), ('RESERVA_APROBACION', 'Reserva Aprobada/Rechazada'), ('RESERVA_AVISO_ADMIN', 'Aviso a Admin de Nueva Reserva'), ('RESERVA_RECORDATORIO', 'Recordatorio de Reserva (Automático)'), ('ALERTA_VENCIMIENTO_VEHICULO', 'Alerta de Vencimiento de Documento Vehicular'), ('TEST', 'Correo de Prueba')], max_length=50, unique=True, verbose_name='Propósito')),
                ('emails_adicionales', models.TextField(blank=True, default='', help_text='Correos externos o institucionales separados por coma, punto y coma o salto de línea.', verbose_name='Emails adicionales')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('grupos', models.ManyToManyField(blank=True, to='auth.group', verbose_name='Grupos destinatarios')),
                ('usuarios', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuarios destinatarios')),
            ],
            options={
                'verbose_name': 'Destinatarios de Correo Operativo',
                'verbose_name_plural': 'Destinatarios de Correos Operativos',
            },
        ),
    ]
