# Generated by Django 5.2.1 on 2026-05-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0004_destinatarioscorreooperativo'),
        ('funcionarios', '0005_funcionario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatarioscorreooperativo',
            name='grupos',
            field=models.ManyToManyField(blank=True, to='funcionarios.grupo', verbose_name='Grupos destinatarios'),
        ),
    ]
