# Generated by Django 5.2.16 on 2026-08-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0005_alter_destinatarioscorreooperativo_grupos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentasmtp',
            options={'ordering': ['nombre'], 'verbose_name': 'Cuenta SMTP', 'verbose_name_plural': 'Cuentas SMTP'},
        ),
        migrations.AlterModelOptions(
            name='destinatarioscorreooperativo',
            options={'ordering': ['proposito'], 'verbose_name': 'Destinatarios de Correo Operativo', 'verbose_name_plural': 'Destinatarios de Correos Operativos'},
        ),
        migrations.AlterModelOptions(
            name='plantillacorreo',
            options={'ordering': ['proposito'], 'verbose_name': 'Plantilla de Correo', 'verbose_name_plural': 'Plantillas de Correo'},
        ),
    ]
