# Generated by Django 5.2.16 on 2026-08-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0006_alter_cuentasmtp_options_and_more'),
        ('comunicaciones', '0010_plantilla_envio_sin_paren_establecimiento'),
    ]

    operations = [
    ]
