# Generated by Django 5.2.1 on 2026-04-29 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_alter_registromensual_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(default=2024, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='nro_chasis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='nro_motor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='VehiculoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('permiso_circulacion', 'Permiso de Circulación'), ('soap', 'SOAP'), ('seguro', 'Seguro'), ('padron', 'Padrón'), ('revision_tecnica', 'Revisión Técnica'), ('mantencion', 'Mantención'), ('otros', 'Otros')], max_length=50)),
                ('archivo', models.FileField(upload_to='vehiculos/documentos/')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Documento de Vehículo',
                'verbose_name_plural': 'Documentos de Vehículos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
