# Generated by Django 5.2.1 on 2026-04-29 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_vehiculo_anio_vehiculo_nro_chasis_vehiculo_nro_motor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoTipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(default='FileText', max_length=50)),
                ('color', models.CharField(default='indigo', max_length=20)),
                ('requerido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.AlterField(
            model_name='vehiculodocumento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='vehiculos.vehiculotipodocumento'),
        ),
    ]
