# Generated by Django 5.2.1 on 2026-04-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_vehiculotipodocumento_alter_vehiculodocumento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoTipoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Combustible',
                'verbose_name_plural': 'Tipos de Combustible',
            },
        ),
    ]
