# Generated by Django 5.2.1 on 2026-04-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_vehiculotipocombustible'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/fotos/'),
        ),
    ]
