# Generated by Django 5.2.1 on 2026-04-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_vehiculo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculodocumento',
            name='dias_aviso',
            field=models.PositiveIntegerField(blank=True, help_text='Personalizar días de aviso (si está vacío usa el defecto del tipo)', null=True),
        ),
        migrations.AddField(
            model_name='vehiculodocumento',
            name='ultima_notificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculotipodocumento',
            name='dias_aviso_defecto',
            field=models.PositiveIntegerField(default=15, help_text='Días antes del vencimiento para avisar'),
        ),
    ]
