# Generated by Django 5.2.1 on 2026-04-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('url', models.URLField(verbose_name='URL')),
                ('icono', models.CharField(default='Link', help_text='Nombre del icono de Lucide (ej: Link, Globe, Box)', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Link de Interés',
                'verbose_name_plural': 'Links de Interés',
                'ordering': ['orden', 'titulo'],
            },
        ),
    ]
