# Generated by Django 5.2.1 on 2026-04-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_mfa_all', models.BooleanField(default=False, verbose_name='Forzar MFA para todos los usuarios')),
            ],
            options={
                'verbose_name': 'Configuración de Seguridad',
                'verbose_name_plural': 'Configuraciones de Seguridad',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='mfa_enforced',
            field=models.BooleanField(default=False, verbose_name='MFA Obligatorio (Admin)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mfa_method',
            field=models.CharField(choices=[('TOTP', 'App de Autenticación'), ('EMAIL', 'Correo Electrónico')], max_length=20, verbose_name='Método MFA Preferido'),
        ),
    ]
