# Generated by Django 5.2.1 on 2026-04-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mfasession'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfasession',
            name='method',
            field=models.CharField(default='EMAIL', max_length=20),
        ),
    ]
