# Generated by Django 5.2.1 on 2026-05-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emailconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='reservas_admin_email',
            field=models.CharField(default='ssgg@slepiquique.cl', help_text='Emails que reciben avisos (separar por comas para varios)', max_length=500, verbose_name='Emails Admin Reservas'),
        ),
    ]
