# Generated by Django 5.2.1 on 2026-05-13 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_emailconfiguration_reservas_admin_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Asset')),
                ('archivo', models.ImageField(upload_to='report_assets/', verbose_name='Archivo de Imagen')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset de Documento',
                'verbose_name_plural': 'Assets de Documentos',
            },
        ),
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('RC_BASIC', 'Recepción Conforme (Servicios Básicos/Pagos)'), ('RC_ADQ', 'Recepción Conforme (Adquisiciones/Facturas)'), ('ACTA_CONTRATO', 'Acta de Conformidad (Contratos)'), ('ORDEN_PAGO', 'Orden de Pago')], max_length=50, unique=True, verbose_name='Tipo de Reporte')),
                ('color_primario', models.CharField(default='#000000', help_text='Color hexadecimal para franjas o detalles (ej: #004488)', max_length=7, verbose_name='Color Primario')),
                ('color_secundario', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color Secundario')),
                ('logo_derecho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logos_derechos', to='core.documentasset', verbose_name='Logo Derecho (Encabezado)')),
                ('logo_izquierdo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logos_izquierdos', to='core.documentasset', verbose_name='Logo Izquierdo (Encabezado)')),
                ('logo_pie_pagina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logos_pie', to='core.documentasset', verbose_name='Logo Pie de Página')),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
            },
        ),
    ]
