# Generated by Django 5.2.1 on 2026-07-07 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreachReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Incidente')),
                ('descripcion', models.TextField(verbose_name='Descripción Técnica / Vulnerabilidad')),
                ('fecha_incidente', models.DateTimeField(verbose_name='Fecha/Hora Estimada del Incidente')),
                ('fecha_descubrimiento', models.DateTimeField(verbose_name='Fecha/Hora de Descubrimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('estimacion_afectados', models.PositiveIntegerField(default=0, verbose_name='Número Estimado de Afectados')),
                ('datos_comprometidos', models.TextField(help_text='Ej: Nombres, RUT, claves, etc.', verbose_name='Categorías de Datos Afectados')),
                ('medidas_mitigacion', models.TextField(verbose_name='Medidas de Solución / Mitigación Adoptadas')),
                ('notificado_agencia', models.BooleanField(default=False, verbose_name='Reportado a la Agencia (APDP)')),
                ('fecha_notificacion_agencia', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Reporte a la Agencia')),
                ('notificado_titulares', models.BooleanField(default=False, verbose_name='Notificado a los Funcionarios Afectados')),
                ('fecha_notificacion_titulares', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Notificación a Titulares')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por')),
            ],
            options={
                'verbose_name': 'Reporte de Brecha de Seguridad',
                'verbose_name_plural': 'Reportes de Brechas de Seguridad',
                'ordering': ['-fecha_descubrimiento'],
            },
        ),
    ]
