# Generated by Django 5.2.1 on 2026-07-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_breachreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acepto_terminos',
            field=models.BooleanField(default=False, verbose_name='Aceptó Políticas de Privacidad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aceptación'),
        ),
    ]
