# Generated by Django 5.2.1 on 2026-07-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_acepto_terminos_profile_fecha_aceptacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiberseguridadCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campana', models.CharField(max_length=200, verbose_name='Nombre de la Campaña')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Capacitación / Ciberhigiene')),
                ('documento', models.FileField(blank=True, null=True, upload_to='ciberseguridad/capacitaciones/', verbose_name='Material Adjunto')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de Término')),
            ],
            options={
                'verbose_name': 'Campaña de Ciberhigiene',
                'verbose_name_plural': 'Campañas de Ciberhigiene',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CiberseguridadPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Plan')),
                ('tipo', models.CharField(choices=[('CONTINUIDAD', 'Continuidad Operacional'), ('RECUPERACION', 'Recuperación ante Desastres (DRP)'), ('RIESGOS', 'Gestión de Riesgos'), ('OTRO', 'Otro Plan')], max_length=50, verbose_name='Tipo de Plan')),
                ('documento', models.FileField(upload_to='ciberseguridad/planes/', verbose_name='Documento (PDF)')),
                ('fecha_aprobacion', models.DateField(verbose_name='Fecha de Aprobación')),
                ('fecha_proxima_revision', models.DateField(verbose_name='Fecha Próxima Revisión')),
                ('activo', models.BooleanField(default=True, verbose_name='Plan Activo')),
            ],
            options={
                'verbose_name': 'Plan de Ciberseguridad',
                'verbose_name_plural': 'Planes de Ciberseguridad',
                'ordering': ['fecha_proxima_revision'],
            },
        ),
        migrations.AlterModelOptions(
            name='breachreport',
            options={'ordering': ['-fecha_descubrimiento'], 'verbose_name': 'Reporte de Incidente / Brecha', 'verbose_name_plural': 'Reportes de Incidentes y Brechas'},
        ),
        migrations.AddField(
            model_name='breachreport',
            name='estado_csirt',
            field=models.CharField(choices=[('NO_REPORTADO', 'No Reportado'), ('ALERTA_TEMPRANA', 'Alerta Temprana (3h)'), ('ACTUALIZACION', 'Actualización (72h)'), ('INFORME_FINAL', 'Informe Final (15 días)')], default='NO_REPORTADO', max_length=50, verbose_name='Estado Reporte CSIRT'),
        ),
        migrations.AddField(
            model_name='breachreport',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AddField(
            model_name='breachreport',
            name='fecha_alerta_temprana',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Alerta Temprana'),
        ),
        migrations.AddField(
            model_name='breachreport',
            name='fecha_informe_final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Informe Final'),
        ),
        migrations.AddField(
            model_name='breachreport',
            name='gravedad_incidente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Gravedad / Impacto Inicial'),
        ),
        migrations.AddField(
            model_name='breachreport',
            name='tipo_amenaza',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo de Amenaza (Ej. Ransomware, Phishing)'),
        ),
        migrations.AlterField(
            model_name='breachreport',
            name='fecha_notificacion_agencia',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Reporte a la Agencia APDP'),
        ),
    ]
