# Generated by Django 5.2.1 on 2026-07-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ciberseguridadcapacitacion_ciberseguridadplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breachreport',
            name='datos_comprometidos',
            field=models.TextField(blank=True, help_text='Ej: Nombres, RUT, claves, etc.', null=True, verbose_name='Categorías de Datos Afectados'),
        ),
        migrations.AlterField(
            model_name='breachreport',
            name='medidas_mitigacion',
            field=models.TextField(blank=True, null=True, verbose_name='Medidas de Solución / Mitigación Adoptadas'),
        ),
    ]
