# Generated by Django 5.2.10 on 2026-02-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_documentocontrato_historialcontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='nro_oc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Orden de Compra (Única)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_oc',
            field=models.CharField(choices=[('UNICA', 'OC Única'), ('MULTIPLE', 'OC Múltiple')], default='UNICA', max_length=20, verbose_name='Tipo de OC'),
        ),
    ]
