# Generated by Django 5.2.10 on 2026-02-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_contrato_establecimientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cdp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº CDP'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nro_oc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de OC'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_oc',
            field=models.CharField(choices=[('UNICA', 'OC Única'), ('MULTIPLE', 'OC Múltiple')], default='AGREEMENT', max_length=10, verbose_name='Tipo de OC'),
        ),
    ]
