# Generated by Django 5.2.10 on 2026-01-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_historialrecepcionconforme'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionconforme',
            name='estado',
            field=models.CharField(choices=[('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=20),
        ),
    ]
