# Generated by Django 5.2.10 on 2026-01-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_cdp_anio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='recepcionconforme',
            options={'ordering': ['-created_at'], 'verbose_name': 'Recepción Conforme', 'verbose_name_plural': 'Recepciones Conformes'},
        ),
        migrations.AlterModelOptions(
            name='registropago',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Registro de Pago', 'verbose_name_plural': 'Registros de Pagos'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documento'},
        ),
        migrations.AlterModelOptions(
            name='tipoproveedor',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Proveedor', 'verbose_name_plural': 'Tipos de Proveedores'},
        ),
    ]
