# Generated by Django 5.2.10 on 2026-02-10 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_grupo_funcionario_grupos'),
        ('servicios', '0012_facturaadquisicion_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaadquisicion',
            name='grupo_firmante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_adquisicion', to='funcionarios.grupo', verbose_name='Grupo de Firmantes'),
        ),
    ]
