# Generated by Django 5.2.10 on 2026-02-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_recepcionconforme_grupo_firmante'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaadquisicion',
            name='nro_factura',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Número de Factura'),
        ),
        migrations.AddField(
            model_name='facturaadquisicion',
            name='nro_oc',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Orden de Compra'),
        ),
    ]
