# Generated by Django 5.2.10 on 2026-02-11 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_remove_grupo_es_firmante_grupo_jefe'),
        ('servicios', '0015_facturaadquisicion_nro_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaadquisicion',
            name='firmante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_firmadas', to='funcionarios.funcionario', verbose_name='Firmante'),
        ),
        migrations.AddField(
            model_name='recepcionconforme',
            name='firmante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rcs_firmadas', to='funcionarios.funcionario', verbose_name='Firmante'),
        ),
    ]
