# Generated by Django 5.2.10 on 2026-02-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_contrato_nro_oc_contrato_tipo_oc'),
        ('servicios', '0016_facturaadquisicion_firmante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaadquisicion',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='contratos.contrato', verbose_name='Contrato Asociado'),
        ),
    ]
