# Generated by Django 5.2.10 on 2026-02-12 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0008_alter_establecimiento_tipo'),
        ('servicios', '0017_facturaadquisicion_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaadquisicion',
            name='establecimientos',
            field=models.ManyToManyField(blank=True, related_name='facturas_adquisicion_m2m', to='establecimientos.establecimiento', verbose_name='Establecimientos'),
        ),
        migrations.AddField(
            model_name='facturaadquisicion',
            name='periodo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='facturaadquisicion',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_adquisicion', to='establecimientos.establecimiento'),
        ),
    ]
