# Generated by Django 5.2.10 on 2026-02-12 19:44

from django.db import migrations


def migrate_establecimientos(apps, schema_editor):
    FacturaAdquisicion = apps.get_model('servicios', 'FacturaAdquisicion')
    for factura in FacturaAdquisicion.objects.all():
        if factura.establecimiento:
            factura.establecimientos.add(factura.establecimiento)

class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0018_facturaadquisicion_establecimientos_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_establecimientos),
    ]
