# Generated by Django 5.2.10 on 2026-02-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0019_migrate_establecimientos_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaadquisicion',
            name='periodo',
            field=models.DateField(blank=True, null=True, verbose_name='Periodo'),
        ),
    ]
