# Generated by Django 5.2.1 on 2026-03-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0020_alter_facturaadquisicion_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('ver_inicio', 'Ver Módulo Inicio'), ('ver_llaves', 'Ver Módulo Préstamo de Llaves'), ('ver_establecimientos', 'Ver Módulo Establecimientos'), ('ver_contratos', 'Ver Módulo Contratos y Finanzas'), ('ver_servicios', 'Ver Módulo Servicios Generales'), ('ver_funcionarios', 'Ver Módulo Funcionarios'), ('ver_telecomunicaciones', 'Ver Módulo Telecomunicaciones'), ('ver_impresoras', 'Ver Módulo Impresoras'), ('ver_vehiculos', 'Ver Módulo Vehículos'), ('ver_tesoreria', 'Ver Módulo Tesorería'), ('ver_licitaciones', 'Ver Módulo Licitaciones'), ('ver_visor_oc', 'Ver Módulo Visor OC'), ('ver_reservas', 'Ver Módulo Reservas'), ('ver_personal_ti', 'Ver Módulo Personal TI'), ('ver_administracion', 'Ver Módulo Administración')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
