# Generated by Django 5.2.1 on 2026-03-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0021_menusistema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuSistema',
        ),
    ]
