# Generated by Django 5.2.1 on 2026-05-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0025_remove_registropago_es_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionconforme',
            name='tipo_rc',
            field=models.CharField(choices=[('ESTANDAR', 'Estándar (Resumen por Servicio)'), ('PAGO', 'Pago (Detalle con Intereses)')], default='ESTANDAR', max_length=20),
        ),
    ]
