# Generated by Django 5.2.1 on 2026-05-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0026_recepcionconforme_tipo_rc'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionconforme',
            name='archivo_escaneado',
            field=models.FileField(blank=True, null=True, upload_to='rcs/escaneadas/%Y/', verbose_name='Recepción Firmada (Escaneada)'),
        ),
        migrations.AlterField(
            model_name='recepcionconforme',
            name='estado',
            field=models.CharField(choices=[('EMITIDA', 'Emitida'), ('COMPLETADA', 'Completada (Firmada)'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=20),
        ),
    ]
