# Generated by Django 5.2.1 on 2026-05-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0027_recepcionconforme_archivo_escaneado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='pagos/comprobantes/%Y/%m/', verbose_name='Comprobante / Boleta Escaneada'),
        ),
    ]
