# Generated by Django 5.2.1 on 2026-05-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0028_registropago_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropago',
            name='consumo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Consumo del periodo'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Medida de Consumo'),
        ),
    ]
