# Generated by Django 5.2.1 on 2026-07-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0029_registropago_consumo_servicio_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcionconforme',
            name='estado',
            field=models.CharField(choices=[('EMITIDA', 'Emitida'), ('COMPLETADA', 'Completada (Firmada)'), ('ANULADA', 'Anulada'), ('HISTORICA', 'Histórica')], default='EMITIDA', max_length=20),
        ),
    ]
