# Generated by Django 5.2.16 on 2026-08-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0030_alter_recepcionconforme_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoentrega',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Entrega', 'verbose_name_plural': 'Tipos de Entrega'},
        ),
    ]
