# Generated by Django 5.2.15 on 2026-08-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0030_alter_recepcionconforme_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaadquisicion',
            name='modalidad',
            field=models.CharField(choices=[('SIN_OC', 'Factura sin OC'), ('COMPRA_AGIL', 'Compra ágil')], db_index=True, default='SIN_OC', help_text='SIN_OC → RCF; COMPRA_AGIL → RCA. Si hay contrato, el folio es ROC.', max_length=20, verbose_name='Modalidad de recepción'),
        ),
    ]
