# Generated by Django 5.2.15 on 2026-08-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0031_facturaadquisicion_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaadquisicion',
            name='cdp',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Certificado de Presupuesto (CDP)'),
        ),
    ]
