# Generated by Django 5.2.16 on 2026-08-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0031_alter_tipoentrega_options'),
        ('servicios', '0032_facturaadquisicion_cdp_optional'),
    ]

    operations = [
    ]
