# Generated by Django 5.2.15 on 2026-09-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0036_facturaadquisicion_periodo_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaadquisicion',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Concepto / glosa de la RC. Opcional: la plantilla puede armar el texto con otras variables.', verbose_name='Descripción de producto o servicio'),
        ),
    ]
