# Generated by Django 5.2.15 on 2026-08-14 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('cuerpo_html', models.TextField(blank=True, default='')),
                ('encabezado_html', models.TextField(blank=True, default='')),
                ('pie_html', models.TextField(blank=True, default='')),
                ('tamano_pagina', models.CharField(choices=[('carta', 'Carta'), ('oficio', 'Oficio'), ('folio', 'Folio'), ('legal', 'Legal'), ('tabloide', 'Tabloide'), ('ejecutivo', 'Ejecutivo'), ('a3', 'A3'), ('a4', 'A4'), ('a5', 'A5'), ('a6', 'A6'), ('b4', 'B4'), ('b5', 'B5'), ('personalizado', 'Personalizado')], default='carta', max_length=20)),
                ('orientacion', models.CharField(choices=[('portrait', 'Vertical'), ('landscape', 'Horizontal')], default='portrait', max_length=12)),
                ('ancho_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Solo para tamaño personalizado', max_digits=7, null=True)),
                ('alto_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Solo para tamaño personalizado', max_digits=7, null=True)),
                ('margen_superior_mm', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('margen_inferior_mm', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('margen_izquierdo_mm', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('margen_derecho_mm', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_documento_editadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_documento_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de documento',
                'verbose_name_plural': 'Plantillas de documentos',
                'ordering': ['nombre'],
                'permissions': [('render_plantilladocumento', 'Puede renderizar plantillas de documento')],
            },
        ),
    ]
