# Generated by Django 5.2.15 on 2026-08-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilladocumento',
            name='proposito',
            field=models.CharField(choices=[('general', 'General'), ('recepcion_adq', 'Recepción de adquisiciones')], db_index=True, default='general', help_text='Módulo / tipo de documento que usará esta plantilla', max_length=40),
        ),
    ]
