# Generated by Django 5.2.15 on 2026-08-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_rlb_tres_propositos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilladocumento',
            name='proposito',
            field=models.CharField(choices=[('borrador', 'Sin asignación (borrador)'), ('recepcion_roc', 'ROC — Recepción con contrato / OC'), ('recepcion_rcf', 'RCF — Recepción sin OC'), ('recepcion_rca', 'RCA — Compra ágil'), ('recepcion_rlb_unitario', 'RLB — Un registro (enviar a pago)'), ('recepcion_rlb', 'RLB — Recepción conforme (1 o más pagos)'), ('recepcion_rlb_junji', 'RLB — Monto JUNJI'), ('recepcion_servicio_colegio', 'Recepción servicio — Colegio'), ('recepcion_servicio_jardin', 'Recepción servicio — Jardín'), ('cobro_transporte_diario', 'Cobro — Transporte diario'), ('cobro_transporte_mensual', 'Cobro — Mensual (asistencia / fijo)'), ('cobro_transporte_mensual_mixto', 'Cobro — Mensual fijo y/o variable')], db_index=True, default='borrador', help_text='Módulo / tipo de documento. «Sin asignación» = borrador.', max_length=40),
        ),
    ]
